# .github/workflows/secret-scan.yml
name: Secret scan
on: [pull_request]
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }   # precisa do histórico
      - name: Install trufflehog
        run: |
          URL=$(curl -s https://api.github.com/repos/trufflesecurity/trufflehog/releases/latest \
            | grep -oP '"browser_download_url":\s*"\K[^"]+linux_amd64\.tar\.gz')
          curl -L "$URL" -o trufflehog.tgz
          tar -xzf trufflehog.tgz
          sudo install -m 0755 trufflehog /usr/local/bin/trufflehog
      - name: Run scan
        run: trufflehog git --only-verified --no-update --branch ${{ github.event.pull_request.base.ref }} .
